const languageStrings = {
    en: {
        home: "Home",
        register: "Register",
        whatsapp_groups: "WhatsApp Groups",
        todays_matches: "Today's Matches",
        betting_codes: "Betting Codes",
        promo_code: "PROMO CODE",
        users: "Users",
        success: "Success",
        visit_paripesa: "Visit PariPesa",
        hero_title: "REGISTER NOW & WIN BIG WITH <span class='rgb-gradient'>PARIPESA</span>",
        hero_subtitle: "Experience the future of sports promotions. Join thousands of winners using our exclusive promo code.",
        exclusive_promo_code: "EXCLUSIVE PROMO CODE:",
        copy_code: "COPY CODE",
        register_on_paripesa: "REGISTER ON PARIPESA",
        join_whatsapp_groups_cta: "JOIN WHATSAPP GROUPS",
        users_joined: "Users Joined",
        winning_codes_shared: "Winning Codes Shared",
        active_members: "Active Members",
        secure_platform: "Secure & Trusted Platform",
        support_available: "24/7 Support Available",
        exclusive_bonuses: "Exclusive Bonuses for New Users",
        how_to_register_title: "HOW TO REGISTER & START WINNING",
        step1_title: "Visit PariPesa",
        step1_desc: "Go to the official PariPesa website or use our direct link.",
        go_to_site: "GO TO SITE",
        step2_title: "Create Account",
        step2_desc: "Fill in your details and create your free account in under 2 minutes.",
        copy_promo_code_vant: "COPY PROMO CODE: VANT",
        step3_title: "Enter Promo Code",
        step3_desc: "During registration, enter the promo code <strong>VANT</strong> to unlock bonuses.",
        copy_code_vant: "COPY CODE VANT",
        step4_title: "Join WhatsApp Groups",
        step4_desc: "Get daily winning codes and tips by joining our exclusive WhatsApp groups.",
        join_groups_cta: "JOIN GROUPS",
        whatsapp_groups_title: "WHATSAPP BETTING GROUPS",
        whatsapp_groups_subtitle: "Join our active communities for daily winning codes, expert tips, and live match discussions.",
        vip_winners_group: "VIP Winners Group",
        vip_group_stats: "248 members • 78% success",
        vip_group_desc: "Exclusive group for serious bettors with high-success rate codes.",
        high_success: "High Success",
        join_now: "JOIN NOW",
        football_predictions_group: "Football Predictions",
        football_group_stats: "512 members • 82% success",
        football_group_desc: "Daily football match predictions and live betting tips.",
        football: "Football",
        daily_tips: "Daily Tips",
        multisport_tips_group: "Multi-Sport Tips",
        multisport_group_stats: "187 members • 75% success",
        multisport_group_desc: "Basketball, Tennis, Cricket and other sports predictions.",
        multisport: "Multi-Sport",
        all_sports: "All Sports",
        todays_hot_matches: "TODAY'S HOT MATCHES",
        todays_matches_subtitle: "Expert predictions for today's most exciting matches",
        exclusive_betting_codes: "EXCLUSIVE BETTING CODES",
        exclusive_codes_subtitle: "Copy these codes directly to your PariPesa account. Updated daily.",
        ai_assistant: "AI Assistant",
        ai_welcome_message: "Hello! I'm your PariPesa Assistant. How can I help you today?",
        ai_try_asking: "Try asking:",
        ai_question1: "How do I register on PariPesa?",
        ai_question2: "What is the promo code?",
        ai_question3: "How do I join WhatsApp groups?",
        type_question: "Type your question...",
        quick_question_register: "How to register?",
        quick_question_promo: "Promo code?",
        quick_question_whatsapp: "WhatsApp groups?",
        footer_desc: "The future of sports promotions. Exclusive bonuses, winning codes, and expert communities.",
        quick_links: "Quick Links",
        how_to_register_link: "How to Register",
        whatsapp_groups_link: "WhatsApp Groups",
        todays_matches_link: "Today's Matches",
        betting_codes_link: "Betting Codes",
        important: "Important",
        official_site: "Official PariPesa Site",
        responsible_betting: "Responsible Betting",
        legal_notice: "Legal Notice",
        contact: "Contact",
        whatsapp_support: "WhatsApp Support",
        available_24_7: "Available 24/7",
        message_us: "Message Us",
        footer_copyright: "© 2050 KREVANT TIPS Promotions. This is a promotional website only.",
        promo_code_footer: "Promo Code:",
        responsible_betting_modal_title: "Responsible Betting",
        responsible_betting_modal_p1: "This is a promotional website only. We do not accept bets or process payments.",
        responsible_betting_modal_p2: "Always gamble responsibly:",
        responsible_betting_modal_li1: "Only bet what you can afford to lose",
        responsible_betting_modal_li2: "Never chase losses",
        responsible_betting_modal_li3: "Set deposit limits",
        responsible_betting_modal_li4: "Take regular breaks",
        responsible_betting_modal_p3: "If you need help with problem gambling, contact professional support services.",
        legal_notice_modal_title: "Legal Notice",
        legal_notice_modal_p1: "This website is for promotional purposes only. All betting activities must be conducted through the official PariPesa platform.",
        legal_notice_modal_p2: "Users must be 18+ and comply with local gambling laws in their jurisdiction.",
        legal_notice_modal_p3: "We are not affiliated with PariPesa; we are an independent promotional agent.",
        legal_notice_modal_p4: "All predictions and codes are for informational purposes only. Past performance does not guarantee future results.",
        welcome_popup_title: "WELCOME TO PARIPESA 2050",
        welcome_popup_subtitle: "Use promo code <strong class='neon-text' style='color: var(--primary-green);'>VANT</strong> for exclusive bonuses!",
        choose_language: "Choose your language:",
        your_welcome: "YOUR WELCOME"
    },
    sw: {
        home: "Nyumbani",
        register: "Jisajili",
        whatsapp_groups: "Magrupu ya WhatsApp",
        todays_matches: "Mechi za Leo",
        betting_codes: "Nambari za Kubeti",
        promo_code: "NAMBARI YA PROMO",
        users: "Watumiaji",
        success: "Mafanikio",
        visit_paripesa: "Tembelea PariPesa",
        hero_title: "JISAJILI SASA & USHINDE ZAIDI NA <span class='rgb-gradient'>PARIPESA</span>",
        hero_subtitle: "Furahia mustakabali wa promosheni za michezo. Jiunge na maelfu ya washindi wanaotumia nambari yetu ya kipekee ya promo.",
        exclusive_promo_code: "NAMBARI YA PROMO YA KIPEKEE:",
        copy_code: "NAKILI NAMBARI",
        register_on_paripesa: "JISAJILI KWENYE PARIPESA",
        join_whatsapp_groups_cta: "JIUNGE NA MAGRUPU YA WHATSAPP",
        users_joined: "Watumiaji Waliojiunga",
        winning_codes_shared: "Nambari za Ushindi Zilizoshirikiwa",
        active_members: "Wajumbe Wanaoshiriki",
        secure_platform: "Jukwaa Salama na la Kuaminika",
        support_available: "Msaada Unapatikana 24/7",
        exclusive_bonuses: "Bonasi za Kipekee kwa Watumiaji Wapya",
        how_to_register_title: "JINSI YA KUJISAJILI & KUANZA KUSHINDA",
        step1_title: "Tembelea PariPesa",
        step1_desc: "Nenda kwenye tovuti rasmi ya PariPesa au tumia kiungo chetu cha moja kwa moja.",
        go_to_site: "NENDA KWENYE TOVUTI",
        step2_title: "Fungua Akaunti",
        step2_desc: "Jaza maelezo yako na ufungue akaunti yako ya bure chini ya dakika 2.",
        copy_promo_code_vant: "NAKILI NAMBARI YA PROMO: VANT",
        step3_title: "Weka Nambari ya Promo",
        step3_desc: "Wakati wa usajili, weka nambari ya promo <strong>VANT</strong> ili kufungua bonasi.",
        copy_code_vant: "NAKILI NAMBARI VANT",
        step4_title: "Jiunge na Magrupu ya WhatsApp",
        step4_desc: "Pata nambari za ushindi za kila siku na vidokezo kwa kujiunga na magrupu yetu ya kipekee ya WhatsApp.",
        join_groups_cta: "JIUNGE NA MAGRUPU",
        whatsapp_groups_title: "MAGRUPU YA KUBETI YA WHATSAPP",
        whatsapp_groups_subtitle: "Jiunge na jamii zetu zinazoshiriki kwa nambari za ushindi za kila siku, vidokezo vya kitaalam, na majadiliano ya mechi mubashara.",
        vip_winners_group: "Grupu la Washindi wa VIP",
        vip_group_stats: "Wajumbe 248 • Mafanikio 78%",
        vip_group_desc: "Grupu la kipekee kwa wachezaji makini wenye nambari za kiwango cha juu cha mafanikio.",
        high_success: "Mafanikio ya Juu",
        join_now: "JIUNGE SASA",
        football_predictions_group: "Utabiri wa Soka",
        football_group_stats: "Wajumbe 512 • Mafanikio 82%",
        football_group_desc: "Utabiri wa mechi za soka za kila siku na vidokezo vya kubeti mubashara.",
        football: "Soka",
        daily_tips: "Vidokezo vya Kila Siku",
        multisport_tips_group: "Vidokezo vya Michezo Mbalimbali",
        multisport_group_stats: "Wajumbe 187 • Mafanikio 75%",
        multisport_group_desc: "Utabiri wa Mpira wa Kikapu, Tenisi, Kriketi na michezo mingine.",
        multisport: "Michezo Mbalimbali",
        all_sports: "Michezo Yote",
        todays_hot_matches: "MECHI MOTO ZA LEO",
        todays_matches_subtitle: "Utabiri wa kitaalam kwa mechi za leo za kusisimua zaidi",
        exclusive_betting_codes: "NAMBARI ZA KIPEKEE ZA KUBETI",
        exclusive_codes_subtitle: "Nakili nambari hizi moja kwa moja kwenye akaunti yako ya PariPesa. Zinasasishwa kila siku.",
        ai_assistant: "Msaidizi wa AI",
        ai_welcome_message: "Habari! Mimi ni Msaidizi wako wa PariPesa. Naweza kukusaidiaje leo?",
        ai_try_asking: "Jaribu kuuliza:",
        ai_question1: "Ninajisajilije kwenye PariPesa?",
        ai_question2: "Nambari ya promo ni ipi?",
        ai_question3: "Ninajiungaje na magrupu ya WhatsApp?",
        type_question: "Andika swali lako...",
        quick_question_register: "Jinsi ya kujisajili?",
        quick_question_promo: "Nambari ya promo?",
        quick_question_whatsapp: "Magrupu ya WhatsApp?",
        footer_desc: "Mustakabali wa promosheni za michezo. Bonasi za kipekee, nambari za ushindi, na jamii za kitaalam.",
        quick_links: "Viungo vya Haraka",
        how_to_register_link: "Jinsi ya Kujisajili",
        whatsapp_groups_link: "Magrupu ya WhatsApp",
        todays_matches_link: "Mechi za Leo",
        betting_codes_link: "Nambari za Kubeti",
        important: "Muhimu",
        official_site: "Tovuti Rasmi ya PariPesa",
        responsible_betting: "Kucheza kwa Wajibu",
        legal_notice: "Notisi ya Kisheria",
        contact: "Mawasiliano",
        whatsapp_support: "Msaada wa WhatsApp",
        available_24_7: "Inapatikana 24/7",
        message_us: "Tutumie Ujumbe",
        footer_copyright: "© 2050 Promosheni za PariPesa. Hii ni tovuti ya promosheni pekee.",
        promo_code_footer: "Nambari ya Promo:",
        responsible_betting_modal_title: "Kucheza kwa Wajibu",
        responsible_betting_modal_p1: "Hii ni tovuti ya promosheni pekee. Hatukubali dau au kuchakata malipo.",
        responsible_betting_modal_p2: "Daima cheza kamari kwa kuwajibika:",
        responsible_betting_modal_li1: "Cheza kamari na kiasi unachoweza kumudu kupoteza",
        responsible_betting_modal_li2: "Kamwe usifukuze hasara",
        responsible_betting_modal_li3: "Weka viwango vya amana",
        responsible_betting_modal_li4: "Pumzika mara kwa mara",
        responsible_betting_modal_p3: "Ikiwa unahitaji msaada na shida ya kucheza kamari, wasiliana na huduma za msaada wa kitaalam.",
        legal_notice_modal_title: "Notisi ya Kisheria",
        legal_notice_modal_p1: "Tovuti hii ni kwa madhumuni ya uendelezaji tu. Shughuli zote za kubeti lazima zifanyike kupitia jukwaa rasmi la PariPesa.",
        legal_notice_modal_p2: "Watumiaji lazima wawe na umri wa miaka 18+ na kuzingatia sheria za kamari za eneo lao.",
        legal_notice_modal_p3: "Hatuna uhusiano na PariPesa; sisi ni wakala huru wa uendelezaji.",
        legal_notice_modal_p4: "Utabiri wote na nambari ni kwa madhumuni ya habari tu. Utendaji wa zamani hauhakikishi matokeo ya baadaye.",
        welcome_popup_title: "KARIBU KREVANT TIPS",
        welcome_popup_subtitle: "Tumia nambari ya promo <strong class='neon-text' style='color: var(--primary-green);'>VANT</strong> kwa bonasi za kipekee!",
        choose_language: "Chagua lugha yako:",
        your_welcome: "KARIBU"
    }
};
